# Generated by Django 4.1 on 2022-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='Нет информации', max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, default='Нет информации', max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
